import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
        <main>
          <img src="https://m.media-amazon.com/images/M/MV5BYzRmMDZhNmUtNmEyNS00MmI4LTlhYTItZDRmOWY5YTU2Y2RjXkEyXkFqcGdeQXRyYW5zY29kZS13b3JrZmxvdw@@._V1_.jpg" alt="" />
        </main>
    
    </div>
  )
}

export default Home