import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styled from "@emotion/styled";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <main>
          <img src="https://m.media-amazon.com/images/M/MV5BYzRmMDZhNmUtNmEyNS00MmI4LTlhYTItZDRmOWY5YTU2Y2RjXkEyXkFqcGdeQXRyYW5zY29kZS13b3JrZmxvdw@@._V1_.jpg" alt="" />
        </main>
      </Container>
    </div>
  )
}

export default Home

const Container = styled.div`
  img{
    max-width:100%;

  }
`